[jenkins]
jenkins ansible_host=107.20.105.146 ansible_user=ubuntu ansible_ssh_private_key_file=/workspaces/aupp-lms-devops-cicd/terraform-setup/secrets/ssh/devop-final-key.pem ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[sonarqube]
sonarqube ansible_host=54.82.189.42 ansible_user=ubuntu ansible_ssh_private_key_file=/workspaces/aupp-lms-devops-cicd/terraform-setup/secrets/ssh/devop-final-key.pem ansible_python_interpreter=/usr/bin/python3 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
